version: "3"
services:
  mqtt5:
    image: eclipse-mosquitto
    hostname: mosquitto
    restart: unless-stopped
    volumes:
      - ./mqtt-broker-pda/config:/mosquitto/config:rw
      - ./mqtt-broker-pda/data:/mosquitto/data:rw
      - ./mqtt-broker-pda/log:/mosquitto/log:rw
    networks:
      default:
        ipv4_address: 172.32.0.2
  rhasspy:
    image: "rhasspy/rhasspy"
    hostname: rhasspy
    restart: unless-stopped
    volumes:
      - "./profiles:/profiles"
      - "/etc/localtime:/etc/localtime:ro"
    command: --user-profiles /profiles --profile de
    networks:
      default:
        ipv4_address: 172.32.0.3
  agent:
    image: "seven/agent"
    hostname: agent
    build: ./agent
    networks:
      default:
        ipv4_address: 172.32.0.4
    depends_on:
      - mqtt5
      - news
      - morning
      - rhasspy
  news:
    image: "drenis/news"
    hostname: news
    build: ./news
    networks:
      default:
        ipv4_address: 172.32.0.5
    depends_on:
      - mongo
  morning:
    image: "martin/morning"
    hostname: morning
    build: ./morning
    networks:
      default:
        ipv4_address: 172.32.0.7
  mongo:
    image: mongo
    hostname: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      default:
        ipv4_address: 172.32.0.6
  spotify:
    image: "tobi/spotify"
    hostname: spotify
    build: ./MicroService_Spotify
    depends_on:
      - mqtt5
    networks:
      default:
        ipv4_address: 172.32.0.8
  calendar:
    image: "tobi/calendar"
    hostname: calendar
    build: ./MicroService_GoogleCalendar
    depends_on:
      - mqtt5
    networks:
      default:
        ipv4_address: 172.32.0.9
networks:
  default:
    name: pda_network
    ipam:
      config:
        - subnet: 172.32.0.0/16
          gateway: 172.32.0.1
